/* Datos de la carta. Editar acá — index.html no tiene ningún trago escrito a mano.
   Los `key` de ingredientes atan la línea de resumen, la receta y el stock de la barra. */

const INGREDIENTS = {
  tequila:     { short: "tequila",          full: "Tequila blanco" },
  "triple-sec":{ short: "triple sec",       full: "Triple sec" },
  ron:         { short: "ron oscuro",       full: "Ron oscuro" },
  prosecco:    { short: "prosecco",         full: "Prosecco" },
  aperol:      { short: "Aperol",           full: "Aperol" },
  campari:     { short: "Campari",          full: "Campari" },
  fernet:      { short: "Fernet Branca",    full: "Fernet Branca" },
  cola:        { short: "coca cola",        full: "Coca Cola" },
  ginger:      { short: "ginger beer",      full: "Ginger beer" },
  soda:        { short: "soda",             full: "Soda" },
  naranja:     { short: "jugo de naranja",  full: "Jugo de naranja" },
  lima:        { short: "lima",             full: "Jugo de lima fresco" },
  granadina:   { short: "granadina",        full: "Granadina" },
  almibar:     { short: "azúcar",           full: "Almíbar simple" },
};

const CATEGORIES = [
  { key: "citrico",   icon: "🍋", title: "Cítricos & Clásicos",   desc: "Frescos, ácidos, directo al punto" },
  { key: "burbujas",  icon: "✨", title: "Burbujas & Spritz",     desc: "Con prosecco, livianos y para brindar" },
  { key: "amargo",    icon: "🔥", title: "Amargos & Intensos",    desc: "Para los que le meten sin miedo" },
  { key: "especiado", icon: "🫚", title: "Especiados & Mules",    desc: "Con jengibre, picantes y refrescantes" },
  { key: "oscuro",    icon: "🥃", title: "Oscuros & Roneros",     desc: "Con ron, cola, y la noche por delante" },
];

/* El número de cada trago sale del orden de esta lista.
   `summary` es opcional: si no está, la línea de ingredientes sale de la receta. */
const DRINKS = [
  {
    name: "Margarita",
    cat: "citrico",
    tag: "★ clásico",
    summary: ["tequila", "triple-sec", "lima"],
    recipe: [["2 oz", "tequila"], ["1 oz", "triple-sec"], ["¾ oz", "lima"]],
    method: "Shaken · Copa con borde de sal",
    steps: "Agitar todo con hielo en la coctelera. Colar en copa escarchada con sal. Decorar con rodaja de lima.",
  },
  {
    name: "Tequila Sunrise",
    cat: "citrico",
    tag: "suave",
    summary: ["tequila", "naranja", "granadina"],
    recipe: [["2 oz", "tequila"], ["4 oz", "naranja"], ["½ oz", "granadina"]],
    method: "Layered · Vaso highball",
    steps: "Servir tequila y jugo de naranja sobre hielo, revolver. Verter la granadina lentamente por el borde — se hunde sola creando el efecto “amanecer”. No revolver.",
  },
  {
    name: "Dark Daiquiri",
    cat: "citrico",
    tag: "potente",
    summary: ["ron", "lima", "almibar"],
    recipe: [["2 oz", "ron"], ["1 oz", "lima"], ["¾ oz", "almibar"]],
    method: "Shaken · Copa cocktail",
    steps: "Agitar todo con hielo en la coctelera. Colar en copa fría. Decorar con rodaja de lima.",
  },
  {
    name: "Aperol Spritz",
    cat: "burbujas",
    tag: "★ favorito",
    summary: ["aperol", "prosecco", "soda"],
    recipe: [["3 oz", "prosecco"], ["2 oz", "aperol"], ["1 oz", "soda"]],
    method: "Built · Copa de vino grande",
    steps: "Llenar la copa con hielo. Agregar prosecco, Aperol, y soda. Revolver suavemente. Decorar con rodaja de naranja.",
  },
  {
    name: "Campari Spritz",
    cat: "burbujas",
    tag: "amargo",
    summary: ["campari", "prosecco", "soda"],
    recipe: [["3 oz", "prosecco"], ["2 oz", "campari"], ["1 oz", "soda"]],
    method: "Built · Copa de vino grande",
    steps: "Igual que el Aperol Spritz pero con Campari. Más amargo e intenso. Decorar con rodaja de naranja.",
  },
  {
    name: "Double Trouble Spritz",
    cat: "burbujas",
    tag: "de la casa",
    summary: ["aperol", "campari", "prosecco"],
    recipe: [["3 oz", "prosecco"], ["1 oz", "aperol"], ["1 oz", "campari"], ["1 oz", "soda"]],
    method: "Built · Copa de vino grande",
    steps: "Llenar con hielo. Prosecco, Aperol, Campari, soda. Revolver suavemente. Decorar con rodaja de naranja.",
  },
  {
    name: "Campari Royale",
    cat: "burbujas",
    tag: "elegante",
    summary: ["campari", "prosecco", "naranja"],
    recipe: [["3 oz", "prosecco"], ["1½ oz", "campari"], ["1½ oz", "naranja"]],
    method: "Built · Copa de vino",
    steps: "Llenar la copa con hielo. Campari y jugo de naranja, revolver. Completar con prosecco. Decorar con rodaja de naranja.",
  },
  {
    name: "Fernet Spritz",
    cat: "burbujas",
    tag: "atrevido",
    summary: ["fernet", "prosecco"],
    recipe: [["3 oz", "prosecco"], ["2 oz", "fernet"], ["1 oz", "soda"]],
    method: "Built · Copa de vino",
    steps: "Llenar con hielo. Fernet, prosecco, soda. Revolver suavemente. Decorar con rodaja de limón.",
  },
  {
    name: "Fernet y Cola",
    cat: "amargo",
    tag: "★ argentino",
    summary: ["fernet", "cola"],
    recipe: [["2 oz", "fernet"], ["4–6 oz", "cola"]],
    method: "Built · Vaso alto",
    steps: "Llenar un vaso alto con hielo. Verter el Fernet. Agregar la Coca Cola inclinando el vaso para generar la espuma dorada. Revolver suave. Proporción clásica argentina: 30% Fernet, 70% Coca.",
  },
  {
    name: "Mexican Mule",
    cat: "especiado",
    tag: "picante",
    summary: ["tequila", "ginger", "lima"],
    recipe: [["2 oz", "tequila"], ["4 oz", "ginger"], ["½ oz", "lima"]],
    method: "Built · Taza de cobre o vaso alto",
    steps: "Llenar con hielo. Tequila y jugo de lima. Completar con ginger beer fría. Revolver suave. Decorar con rodaja de lima.",
  },
  {
    name: "Dark 'n' Stormy",
    cat: "especiado",
    tag: "★ clásico",
    summary: ["ron", "ginger", "lima"],
    recipe: [["1½ oz", "ron"], ["4 oz", "ginger"], ["¼ oz", "lima"]],
    method: "Layered · Vaso highball",
    steps: "Llenar el vaso con hielo. Verter ginger beer y lima. Flotar el ron oscuro lentamente por encima con la cuchara invertida — no revolver. Decorar con rodaja de lima.",
  },
  {
    name: "Cuba Libre",
    cat: "oscuro",
    tag: "★ clásico",
    summary: ["ron", "cola", "lima"],
    recipe: [["2 oz", "ron"], ["4 oz", "cola"], ["½ oz", "lima"]],
    method: "Built · Vaso highball",
    steps: "Exprimir la lima en el vaso. Agregar hielo y ron. Completar con Coca Cola fría. Revolver suavemente. Decorar con cuña de lima.",
  },
];
